config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'user_works#index'
  end

  root to: 'about#index', as: :unauthenticated_root
  
  resources :users, only: :show do
    resources :creators, controller: :user_creators, only: [:index, :new, :create]
    resources :works, controller: :user_works, only: [:index, :new, :create]
  end
  resources :creators, only: [:show, :edit, :update, :destroy] do
    resources :families, only: [:new, :create, :destroy]
  end
  resources :works, only: [:show, :edit, :update, :destroy]
end

app/models/family.rb
class Family < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :relation

  belongs_to :user
  belongs_to :creator

  # 作品の編集・削除権限チェック
  # こども情報の編集・削除権限チェック
  def self.edit_permission_check(family)
    # 「パパ・ママ」のみ
    family && [1, 2].include?(family.relation_id)
  end

  # こどもの家族の解除権限チェック
  def self.remove_family_permission_check(user_family, creator_family)
    # パパ・ママは、自身以外解除可能。
    # パパ・ママ以外は自身とのつながりのみ解除可能
    if user_family && [1, 2].include?(user_family.relation_id)
      user_family.user_id != creator_family.user_id
    else
      user_family.user_id == creator_family.user_id
    end
  end

  # こどもの家族の追加権限チェック
  def self.add_family_permission_check(family)
    # 「パパ・ママ」のみ
    family && [1, 2].include?(family.relation_id)
  end
end

app/models/family_form.rb
class FamilyForm
  include ActiveModel::Model
  include ActiveRecord::AttributeAssignment
  attr_accessor :user_id,
                :creator_id,
                :relation_id,
                :creator_name,
                :creator_date_of_birth,
                :creator_gender_id

  def save
    creator = Creator.create(
      name: creator_name,
      date_of_birth: creator_date_of_birth,
      gender_id: creator_gender_id
    )
    Family.create(
      user_id: user_id,
      creator_id: creator.id,
      relation_id: relation_id
    )
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  def new
    @creator = Creator.find(params[:creator_id])
    @family_user_form = FamilyUserForm.new
  end

  def create
    @family_user_form = FamilyUserForm.new(family_user_form_params)
    # User.exists?(email: @family_user_form.user_email)
    if @family_user_form.valid?
      @family_user_form.save
      redirect_to creator_path(params[:creator_id])
    else
      render :new
    end
  end

  def destroy
    # 【Todo】権限チェック（関係性・ログインユーザー）
    @family = Family.find(params[:id])
    @family.destroy
    redirect_to creator_path(params[:creator_id])
  end

  private

  def family_user_form_params
    params.require(:family_user_form).permit(
      :relation_id,
      :user_email
    ).merge(
      creator_id: params[:creator_id]
    )
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
  # こどもの家族の解除権限チェック
  def remove_family_permission_check(user_family, creator_family)
    Family.remove_family_permission_check(user_family, creator_family)
  end

  # こどもの家族の追加権限チェック
  def add_family_permission_check(family)
    Family.add_family_permission_check(family)
  end
end

app/views/families/new.html.erb
<%= render "shared/header" %>
<div class="container">
<h5 class="screen-name">作品を閲覧できる家族の追加</h5>
<div class="contents">

<%= form_with model: @family_user_form, url: creator_families_path(@creator), local: true do |f| %>

<div class="row">
  <div class="input-field col s12">
    <%= f.text_field :user_email, class: "validate" %>
    <%= f.label :user_email, '追加する家族（登録ユーザー）のemail' %>
  </div>
</div>

<div class="row">
  <div class="col s12 m6 l6 xl6">
    <%= f.label :relation_id, "追加する家族と#{@creator.name}さんとの関係" %>
    <%= f.collection_select(:relation_id, Relation.all, :id, :value, {}, {}) %>
  </div>
</div>

<div class="button_wrapper">
  <%= button_tag '家族の追加', class: 'btn-large waves-effect waves-light', type: 'button', onclick: 'submit();' do %>
    家族の追加<i class="material-icons right">send</i>
  <% end %>
</div>

<% end %>

</div>
</div>