config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'user_works#index'
  end

  root to: 'about#index', as: :unauthenticated_root
  
  resources :users, only: :show do
    resources :creators, controller: :user_creators, only: [:index, :new, :create]
    resources :works, controller: :user_works, only: [:index, :new, :create]
  end
  resources :creators, only: [:show, :edit, :update, :destroy] do
    resources :families, only: [:new, :create, :destroy]
  end
  resources :works, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creator.rb
class Creator < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender

  has_many :families, dependent: :destroy
  has_many :users, through: :families
  has_many :works, dependent: :destroy
end

app/models/family.rb
class Family < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :relation

  belongs_to :user
  belongs_to :creator

  # 作品の編集・削除権限チェック
  # こども情報の編集・削除権限チェック
  def self.edit_permission_check(family)
    # 「パパ・ママ」のみ
    family && [1, 2].include?(family.relation_id)
  end

  # こどもの家族の解除権限チェック
  def self.remove_family_permission_check(user_family, creator_family)
    # パパ・ママは、自身以外解除可能。
    # パパ・ママ以外は自身とのつながりのみ解除可能
    if user_family && [1, 2].include?(user_family.relation_id)
      user_family.user_id != creator_family.user_id
    else
      user_family.user_id == creator_family.user_id
    end
  end

  # こどもの家族の追加権限チェック
  def self.add_family_permission_check(family)
    # 「パパ・ママ」のみ
    family && [1, 2].include?(family.relation_id)
  end
end

app/models/family_creator_form.rb
class FamilyCreatorForm
  include ActiveModel::Model
  include ActiveRecord::AttributeAssignment
  attr_accessor :user_id,
                :creator_id,
                :relation_id,
                :creator_name,
                :creator_date_of_birth,
                :creator_gender_id

  def save
    creator = Creator.create(
      name: creator_name,
      date_of_birth: creator_date_of_birth,
      gender_id: creator_gender_id
    )
    Family.create(
      user_id: user_id,
      creator_id: creator.id,
      relation_id: relation_id
    )
  end
end

app/models/family_form.rb
class FamilyForm
  include ActiveModel::Model
  include ActiveRecord::AttributeAssignment
  attr_accessor :user_id,
                :creator_id,
                :relation_id,
                :creator_name,
                :creator_date_of_birth,
                :creator_gender_id

  def save
    creator = Creator.create(
      name: creator_name,
      date_of_birth: creator_date_of_birth,
      gender_id: creator_gender_id
    )
    Family.create(
      user_id: user_id,
      creator_id: creator.id,
      relation_id: relation_id
    )
  end
end

app/models/family_user_form.rb
class FamilyUserForm
  include ActiveModel::Model
  attr_accessor :user_id,
                :user_email,
                :creator_id,
                :relation_id

  def save
    user_id = User.select(:id).find_by(email: user_email).id
    Family.create(
      user_id: user_id,
      creator_id: creator_id,
      relation_id: relation_id
    )
  end
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, value: '---' },
    { id: 1, value: '男の子' },
    { id: 2, value: '女の子' },
    { id: 3, value: '指定なし' }
  ]
end

app/models/relation.rb
class Relation < ActiveHash::Base
  self.data = [
    { id: 0, value: '---' },
    { id: 1, value: 'パパ' },
    { id: 2, value: 'ママ' },
    { id: 3, value: 'おじいちゃん' },
    { id: 4, value: 'おばあちゃん' },
    { id: 5, value: 'おじさん' },
    { id: 6, value: 'おばさん' },
    { id: 7, value: '子ども自身' },
    { id: 8, value: '親族ほか' }
  ]
end

app/models/scope.rb
class Scope < ActiveHash::Base
  self.data = [
    { id: 1, value: '夫婦のみ', targets: [1, 2] },
    { id: 2, value: '家族みんな', targets: [1, 2, 3, 4, 5, 6, 7, 8] },
    { id: 3, value: '一般公開' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :families, dependent: :destroy
  has_many :creators, through: :families
end

app/models/work.rb
class Work < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :scope

  belongs_to :creator
  has_many_attached :images
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
  def age(creator, start_day = Time.zone.today)
    dob = creator.date_of_birth

    age_years = (start_day.strftime('%Y%m%d').to_i - dob.strftime('%Y%m%d').to_i) / 10_000.to_i
    age_months = (start_day.strftime('%m%d').to_i - dob.strftime('%m%d').to_i) / 100.to_i
    age_months += 12 if age_months.negative?

    "#{age_years}歳#{age_months}ヶ月"
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
  # こどもの家族の解除権限チェック
  def remove_family_permission_check(user_family, creator_family)
    Family.remove_family_permission_check(user_family, creator_family)
  end

  # こどもの家族の追加権限チェック
  def add_family_permission_check(family)
    Family.add_family_permission_check(family)
  end
end

app/helpers/user_works_helper.rb
module UserWorksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
  # 編集・削除権限チェック
  def edit_permission_check(family)
    Family.edit_permission_check(family)
  end

  # 公開範囲表示アイコン
  def work_scope_icon(work)
    icon_string = if work.scope.id == 3
                    'lock_open'
                  else
                    'lock'
                  end
    tag.i(class: 'tiny material-icons') { icon_string }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tottoko</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header>

<nav class="grey lighten-5">
  <div class="nav-wrapper">
    <%= link_to root_path, class: "brand-logoa" do %>
      <%= image_tag "logo.png", class: "logo" %>
    <% end %>
    <a href="#" data-target="mobile-demo" class="light-blue-text text-accent-4 right sidenav-trigger">
      <i class="material-icons">menu</i>
    </a>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "ログイン：#{current_user.name}", user_path(current_user), class: "light-blue-text text-accent-4" %></li>
        <li><%= link_to '作品投稿', new_user_work_path(user_id: current_user), class: "light-blue-text text-accent-4" %></li>
        <li><%= link_to '家族設定', user_creators_path(user_id: current_user), class: "light-blue-text text-accent-4" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "light-blue-text text-accent-4" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "light-blue-text text-accent-4" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "light-blue-text text-accent-4" %></li>
      <% end %>
    </ul>
  </div>
</nav>

<ul class="sidenav right" id="mobile-demo">
  <% if user_signed_in? %>
    <li><%= link_to "ログイン：#{current_user.name}", user_path(current_user), class: "light-blue-text text-accent-4" %></li>
    <li><%= link_to '作品投稿', new_user_work_path(user_id: current_user), class: "light-blue-text text-accent-4" %></li>
    <li><%= link_to '家族設定', user_creators_path(user_id: current_user), class: "light-blue-text text-accent-4" %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "light-blue-text text-accent-4" %></li>
  <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: "light-blue-text text-accent-4" %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: "light-blue-text text-accent-4" %></li>
  <% end %>
</ul>

</header>