config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'user_works#index'
  end

  root to: 'about#index', as: :unauthenticated_root
  
  resources :users, only: :show do
    resources :creators, controller: :user_creators, only: [:index, :new, :create]
    resources :works, controller: :user_works, only: [:index, :new, :create]
  end
  resources :creators, only: [:show, :edit, :update, :destroy] do
    resources :families, only: [:new, :create, :destroy]
  end
  resources :works, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creator.rb
class Creator < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender

  has_many :families, dependent: :destroy
  has_many :users, through: :families
  has_many :works, dependent: :destroy
end

app/models/family.rb
class Family < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :relation

  belongs_to :user
  belongs_to :creator

  # 作品の編集・削除権限チェック
  # こども情報の編集・削除権限チェック
  def self.edit_permission_check(family)
    # 「パパ・ママ」のみ
    family && [1, 2].include?(family.relation_id)
  end

  # こどもの家族の解除権限チェック
  def self.remove_family_permission_check(user_family, creator_family)
    # パパ・ママは、自身以外解除可能。
    # パパ・ママ以外は自身とのつながりのみ解除可能
    if user_family && [1, 2].include?(user_family.relation_id)
      user_family.user_id != creator_family.user_id
    else
      user_family.user_id == creator_family.user_id
    end
  end

  # こどもの家族の追加権限チェック
  def self.add_family_permission_check(family)
    # 「パパ・ママ」のみ
    family && [1, 2].include?(family.relation_id)
  end
end

app/models/family_creator_form.rb
class FamilyCreatorForm
  include ActiveModel::Model
  include ActiveRecord::AttributeAssignment
  attr_accessor :user_id,
                :creator_id,
                :relation_id,
                :creator_name,
                :creator_date_of_birth,
                :creator_gender_id

  def save
    creator = Creator.create(
      name: creator_name,
      date_of_birth: creator_date_of_birth,
      gender_id: creator_gender_id
    )
    Family.create(
      user_id: user_id,
      creator_id: creator.id,
      relation_id: relation_id
    )
  end
end

app/models/family_form.rb
class FamilyForm
  include ActiveModel::Model
  include ActiveRecord::AttributeAssignment
  attr_accessor :user_id,
                :creator_id,
                :relation_id,
                :creator_name,
                :creator_date_of_birth,
                :creator_gender_id

  def save
    creator = Creator.create(
      name: creator_name,
      date_of_birth: creator_date_of_birth,
      gender_id: creator_gender_id
    )
    Family.create(
      user_id: user_id,
      creator_id: creator.id,
      relation_id: relation_id
    )
  end
end

app/models/family_user_form.rb
class FamilyUserForm
  include ActiveModel::Model
  attr_accessor :user_id,
                :user_email,
                :creator_id,
                :relation_id

  def save
    user_id = User.select(:id).find_by(email: user_email).id
    Family.create(
      user_id: user_id,
      creator_id: creator_id,
      relation_id: relation_id
    )
  end
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, value: '---' },
    { id: 1, value: '男の子' },
    { id: 2, value: '女の子' },
    { id: 3, value: '指定なし' }
  ]
end

app/models/relation.rb
class Relation < ActiveHash::Base
  self.data = [
    { id: 0, value: '---' },
    { id: 1, value: 'パパ' },
    { id: 2, value: 'ママ' },
    { id: 3, value: 'おじいちゃん' },
    { id: 4, value: 'おばあちゃん' },
    { id: 5, value: 'おじさん' },
    { id: 6, value: 'おばさん' },
    { id: 7, value: '子ども自身' },
    { id: 8, value: '親族ほか' }
  ]
end

app/models/scope.rb
class Scope < ActiveHash::Base
  self.data = [
    { id: 1, value: '夫婦のみ', targets: [1, 2] },
    { id: 2, value: '家族みんな', targets: [1, 2, 3, 4, 5, 6, 7, 8] },
    { id: 3, value: '一般公開' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :families, dependent: :destroy
  has_many :creators, through: :families
end

app/models/work.rb
class Work < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :scope

  belongs_to :creator
  has_many_attached :images
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/user_creators_controller.rb
class UserCreatorsController < ApplicationController
  def new
    @family_creator_form = FamilyCreatorForm.new
  end

  def create
    @family_creator_form = FamilyCreatorForm.new(family_creator_form_params)
    if @family_creator_form.valid?

      # 【Todo】例外処理（トランザクション処理）実装要
      @family_creator_form.save
      # --------------------------------------------------------

      redirect_to user_works_path(user_id: current_user)
    else
      render :new
    end
  end

  def index
    @user_creators = Creator.where(
      id: Family.where(user_id: current_user.id).select(:creator_id)
    )
  end

  private

  def family_creator_form_params
    params.require(:family_creator_form).permit(
      :creator_name,
      :creator_date_of_birth,
      :creator_gender_id,
      :relation_id
    ).merge(
      user_id: current_user.id
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
  def age(creator, start_day = Time.zone.today)
    dob = creator.date_of_birth

    age_years = (start_day.strftime('%Y%m%d').to_i - dob.strftime('%Y%m%d').to_i) / 10_000.to_i
    age_months = (start_day.strftime('%m%d').to_i - dob.strftime('%m%d').to_i) / 100.to_i
    age_months += 12 if age_months.negative?

    "#{age_years}歳#{age_months}ヶ月"
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
  # こどもの家族の解除権限チェック
  def remove_family_permission_check(user_family, creator_family)
    Family.remove_family_permission_check(user_family, creator_family)
  end

  # こどもの家族の追加権限チェック
  def add_family_permission_check(family)
    Family.add_family_permission_check(family)
  end
end

app/helpers/user_creators_helper.rb
module UserCreatorsHelper
end

app/helpers/user_works_helper.rb
module UserWorksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
  # 編集・削除権限チェック
  def edit_permission_check(family)
    Family.edit_permission_check(family)
  end

  # 公開範囲表示アイコン
  def work_scope_icon(work)
    icon_string = if work.scope.id == 3
                    'lock_open'
                  else
                    'lock'
                  end
    tag.i(class: 'tiny material-icons') { icon_string }
  end
end

app/views/user_creators/index.html.erb
<%= render "shared/header" %>
<div class="container">
<h5 class="screen-name">お子さま一覧</h5>
<div class="contents">

<ul class="creator-unit">
  <% @user_creators.each do |creator| %>
  <li class="creator-lists">
    <div><%= link_to creator.name, creator_path(creator) %></div>
    <div><%= age(creator) %> / <%= creator.date_of_birth.strftime("%Y年%-m月%-d日") %></div>
  </li>
  <% end %>
</ul>
<div class="right-align">
  <%= link_to '+お子さまを追加する', new_user_creator_path(user_id: current_user), class: "new-creator" %>
</div>

</div>
</div>

app/views/user_creators/new.html.erb
<%= render "shared/header" %>
<div class="container">
<h5 class="screen-name">お子さまの追加</h5>
<div class="contents">

<%= form_with model: @family_creator_form, url: user_creators_path(user_id: current_user), local: true do |f| %>

<div class="row">
  <div class="input-field col s12">
    <%= f.text_field :creator_name, class: "validate" %>
    <%= f.label :creator_name, 'お子さまの名前（必須）' %>
  </div>
</div>

<div class="row">
  <div class="col s12 m4 l2 xl2">
  <%= f.label :creator_date_of_birth, '誕生日（必須）' %><br>
    <div class="datetime">
      <%= raw sprintf(
        f.date_select(
          :creator_date_of_birth,
          use_month_numbers: true,
          prompt:'---',
          start_year: Time.now.year,
          end_year: 1930,
          date_separator: '%s',
          class: ""),
        '<span class="text-baseline"> 年 </span>', '<span class="text-baseline"> 月 </span>') + '<span class="text-baseline"> 日 </span>'
      %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m6 l4 xl3">
    <%= f.label :creator_gender_id, '性別' %>
    <%= f.collection_select(:creator_gender_id, Gender.all, :id, :value, {}, {}) %>
  </div>
</div>

<div class="row">
  <div class="col s12 m6 l4 xl3">
    <%= f.label :creator_gender_id, 'こどもとの関係' %>
    <%= f.collection_select(:relation_id, Relation.all, :id, :value, {}, {}) %>
  </div>
</div>

<div class="button_wrapper">
  <%= button_tag '', class: 'btn-large waves-effect waves-light', type: 'button', onclick: 'submit();' do %>
    登録<i class="material-icons right">send</i>
  <% end %>
</div>

<% end %>
</div>
</div>