config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'user_works#index'
  end

  root to: 'about#index', as: :unauthenticated_root
  
  resources :users, only: :show do
    resources :creators, controller: :user_creators, only: [:index, :new, :create]
    resources :works, controller: :user_works, only: [:index, :new, :create]
  end
  resources :creators, only: [:show, :edit, :update, :destroy] do
    resources :families, only: [:new, :create, :destroy]
  end
  resources :works, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creator.rb
class Creator < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender

  has_many :families, dependent: :destroy
  has_many :users, through: :families
  has_many :works, dependent: :destroy
end

app/models/family.rb
class Family < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :relation

  belongs_to :user
  belongs_to :creator

  # 作品の編集・削除権限チェック
  # こども情報の編集・削除権限チェック
  def self.edit_permission_check(family)
    # 「パパ・ママ」のみ
    family && [1, 2].include?(family.relation_id)
  end

  # こどもの家族の解除権限チェック
  def self.remove_family_permission_check(user_family, creator_family)
    # パパ・ママは、自身以外解除可能。
    # パパ・ママ以外は自身とのつながりのみ解除可能
    if user_family && [1, 2].include?(user_family.relation_id)
      user_family.user_id != creator_family.user_id
    else
      user_family.user_id == creator_family.user_id
    end
  end

  # こどもの家族の追加権限チェック
  def self.add_family_permission_check(family)
    # 「パパ・ママ」のみ
    family && [1, 2].include?(family.relation_id)
  end
end

app/models/family_creator_form.rb
class FamilyCreatorForm
  include ActiveModel::Model
  include ActiveRecord::AttributeAssignment
  attr_accessor :user_id,
                :creator_id,
                :relation_id,
                :creator_name,
                :creator_date_of_birth,
                :creator_gender_id

  def save
    creator = Creator.create(
      name: creator_name,
      date_of_birth: creator_date_of_birth,
      gender_id: creator_gender_id
    )
    Family.create(
      user_id: user_id,
      creator_id: creator.id,
      relation_id: relation_id
    )
  end
end

app/models/family_form.rb
class FamilyForm
  include ActiveModel::Model
  include ActiveRecord::AttributeAssignment
  attr_accessor :user_id,
                :creator_id,
                :relation_id,
                :creator_name,
                :creator_date_of_birth,
                :creator_gender_id

  def save
    creator = Creator.create(
      name: creator_name,
      date_of_birth: creator_date_of_birth,
      gender_id: creator_gender_id
    )
    Family.create(
      user_id: user_id,
      creator_id: creator.id,
      relation_id: relation_id
    )
  end
end

app/models/family_user_form.rb
class FamilyUserForm
  include ActiveModel::Model
  attr_accessor :user_id,
                :user_email,
                :creator_id,
                :relation_id

  def save
    user_id = User.select(:id).find_by(email: user_email).id
    Family.create(
      user_id: user_id,
      creator_id: creator_id,
      relation_id: relation_id
    )
  end
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, value: '---' },
    { id: 1, value: '男の子' },
    { id: 2, value: '女の子' },
    { id: 3, value: '指定なし' }
  ]
end

app/models/relation.rb
class Relation < ActiveHash::Base
  self.data = [
    { id: 0, value: '---' },
    { id: 1, value: 'パパ' },
    { id: 2, value: 'ママ' },
    { id: 3, value: 'おじいちゃん' },
    { id: 4, value: 'おばあちゃん' },
    { id: 5, value: 'おじさん' },
    { id: 6, value: 'おばさん' },
    { id: 7, value: '子ども自身' },
    { id: 8, value: '親族ほか' }
  ]
end

app/models/scope.rb
class Scope < ActiveHash::Base
  self.data = [
    { id: 1, value: '夫婦のみ', targets: [1, 2] },
    { id: 2, value: '家族みんな', targets: [1, 2, 3, 4, 5, 6, 7, 8] },
    { id: 3, value: '一般公開' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :families, dependent: :destroy
  has_many :creators, through: :families
end

app/models/work.rb
class Work < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :scope

  belongs_to :creator
  has_many_attached :images
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  def show
    @creator = Creator.find(params[:id])
    @family = Family.find_by(user_id: current_user.id, creator_id: params[:id])
    if @creator && @family
      @creator_families = Family.where(creator_id: params[:id]).includes(:user)
    else
      redirect_to user_creators_path(current_user)
    end
  end

  def edit
    @creator = Creator.find(params[:id])
  end

  def update
    @creator = Creator.find(params[:id])
    if @creator.update(creator_params)
      redirect_to creator_path(@creator)
    else
      render :edit
    end
  end

  def destroy
    @creator = Creator.find(params[:id])
    @creator.destroy
    redirect_to user_works_path(user_id: current_user)
  end

  private

  def creator_params
    params.require(:creator).permit(
      :name,
      :date_of_birth,
      :gender_id
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!,    only: [:edit, :update, :destroy]
  before_action :set_work,              only: [:edit, :update, :destroy, :show]
  before_action :edit_permission_check, only: [:edit, :update, :destroy]

  def show
    @family = Family.find_by(user_id: current_user.id, creator_id: @work.creator_id) if user_signed_in?

    # 閲覧権限チェック
    redirect_to root_path unless @work.scope_id == 3 || (@family && @work.scope.targets.include?(@family.relation_id))
  end

  def edit
  end

  def update
    if @work.update(work_params)
      redirect_to work_path(@work)
    else
      render :edit
    end
  end

  def destroy
    @work.destroy
    redirect_to root_path
  end

  private

  def set_work
    @work = Work.find(params[:id])
  end

  # 編集・削除権限チェック
  def edit_permission_check
    family = Family.find_by(user_id: current_user.id, creator_id: @work.creator_id)
    redirect_to root_path unless Family.edit_permission_check(family)
  end

  def work_params
    params.require(:work).permit(
      :date,
      :title,
      :description,
      :scope_id,
      :creator_id,
      images: []
    )
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
  def age(creator, start_day = Time.zone.today)
    dob = creator.date_of_birth

    age_years = (start_day.strftime('%Y%m%d').to_i - dob.strftime('%Y%m%d').to_i) / 10_000.to_i
    age_months = (start_day.strftime('%m%d').to_i - dob.strftime('%m%d').to_i) / 100.to_i
    age_months += 12 if age_months.negative?

    "#{age_years}歳#{age_months}ヶ月"
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
  # こどもの家族の解除権限チェック
  def remove_family_permission_check(user_family, creator_family)
    Family.remove_family_permission_check(user_family, creator_family)
  end

  # こどもの家族の追加権限チェック
  def add_family_permission_check(family)
    Family.add_family_permission_check(family)
  end
end

app/helpers/user_creators_helper.rb
module UserCreatorsHelper
end

app/helpers/user_works_helper.rb
module UserWorksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
  # 編集・削除権限チェック
  def edit_permission_check(family)
    Family.edit_permission_check(family)
  end

  # 公開範囲表示アイコン
  def work_scope_icon(work)
    icon_string = if work.scope.id == 3
                    'lock_open'
                  else
                    'lock'
                  end
    tag.i(class: 'tiny material-icons') { icon_string }
  end
end

app/views/creators/edit.html.erb
<%= render "shared/header" %>
<div class="container">
<h5 class="screen-name">お子さまの情報編集</h5>
<div class="contents">

<%= form_with model: @creator, local: true do |f| %>

<div class="row">
  <div class="input-field col s12">
    <%= f.text_field :name, class: "validate" %>
    <%= f.label :name, 'お子さまの名前（必須）' %>
  </div>
</div>

<div class="row">
  <div class="col s12 m4 l2 xl2">
  <%= f.label :date_of_birth, '誕生日（必須）' %><br>
    <div class="datetime">
      <%= raw sprintf(
        f.date_select(
          :date_of_birth,
          use_month_numbers: true,
          prompt:'---',
          start_year: Time.now.year,
          end_year: 1930,
          date_separator: '%s',
          class: ""),
        '<span class="text-baseline"> 年 </span>', '<span class="text-baseline"> 月 </span>') + '<span class="text-baseline"> 日 </span>'
      %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m6 l4 xl3">
    <%= f.label :creator_gender_id, '性別' %>
    <%= f.collection_select(:gender_id, Gender.all, :id, :value, {}, {}) %>
  </div>
</div>

<div class="button_wrapper">
  <%= button_tag '', class: 'btn-large waves-effect waves-light', type: 'button', onclick: 'submit();' do %>
    登録<i class="material-icons right">send</i>
  <% end %>
</div>

<% end %>
</div>
</div>

app/views/creators/index.html.erb
<%= render "shared/header" %>

<h1>家族設定</h1>

<h2>お子さま一覧</h2>
<ul>
  <% @user_creators.each do |creator| %>
  <li>
    <p><%= link_to creator.name, creator_path(creator) %></p>
    <p><%= age(creator) %> / <%= creator.date_of_birth.strftime("%Y年%-m月%-d日") %></p>
  </li>
  <% end %>
</ul>
<p><%= link_to 'お子さまを追加する', new_creator_path  %></p>

app/views/creators/new.html.erb
<%= render "shared/header" %>

<h1>お子さまの追加</h1>

<%= form_with model: @family_creator_form, url: creators_path, local: true do |f| %>

<div>
  <label>お子さまの名前*</label>
  <p><%= f.text_field :creator_name %></p>
</div>

<div>
  <label>誕生日*</label>
  <%# <%= f.date_select :creator_date_of_birth, use_month_numbers: true, start_year: 1930, end_year: Time.now.year, default: Date.new(1989, 1, 1) %>
  <p><%= raw sprintf(
    f.date_select(
      :creator_date_of_birth,
        use_month_numbers: true,
        prompt:'---',
        start_year: 1930,
        end_year: Time.now.year,
        date_separator: '%s'),
      "<span> 年 </span>", "<span> 月 </span>") + "<span> 日 </span>"
  %></p>
</div>

<div>
  <label>性別</label>
  <p><%= f.collection_select(:creator_gender_id, Gender.all, :id, :value, {}, {}) %></p>
</div>

<div>
  <label>こどもとの関係*</label>
  <p><%= f.collection_select(:relation_id, Relation.all, :id, :value, {}, {}) %></p>
</div>

<div>
  <%= f.submit '完了' %>
</div>

<% end %>

app/views/creators/show.html.erb
<%= render "shared/header" %>
<div class="container">
<h5 class="screen-name">お子さま情報</h5>
<div class="contents">

<% if self.edit_permission_check(@family) %>
  <div class="right-align">
    <%= link_to '編集', edit_creator_path(@creator) %>
    <span>｜</span>
    <%= link_to '削除', creator_path(@creator), method: :delete %>
  </div>
<% end %>

<div class="attribute">
  <label>お子さまの名前</label><br>
  <%= @creator.name %>
</div>

<div class="attribute">
  <label>誕生日</label><br>
  <%= @creator.date_of_birth.strftime("%Y年%-m月%-d日") %>
</div>

<div class="attribute">
  <label>性別</label><br>
  <%= @creator.gender.value %>
</div>


<table id="family">
  <caption><h6>作品を閲覧できる家族</h6></caption>
  <tr>
    <th>ユーザー名</th>
    <th>お子さまとの関係</th>
    <th>操作</th>
  </tr>
  <% @creator_families.each do |family| %>
  <tr>
    <td><%= family.user.name %></td>
    <td><%= family.relation.value %></td>
    <td>
    <% if remove_family_permission_check(@family, family) %>
      <%= link_to 'つながり解除', creator_family_path(creator_id: family.creator_id, id: family.id), method: :delete %>
    <% end %>
    </td>
  </tr>
  <% end %>
</table>
<% if add_family_permission_check(@family) %>
  <div class="right-align">
    <%= link_to '+閲覧できる家族を追加', new_creator_family_path(@creator) %>
  <div>
<% end %>

</div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="container">
<h5 class="screen-name"><%= @user.name %>さんの情報</h5>
<div class="contents">

<%# 編集ボタンを追加 %>
<div class="right-align">
  <%= link_to '編集', edit_user_registration_path(current_user) %>
</div>

<div class="attribute">
  <label>メールアドレス</label><br>
  <%= @user.email %>
</div>

<div class="attribute">
  <label>名前</label><br>
  <%= @user.name %>
</div>

</div>
</div>

app/views/works/edit.html.erb
<%= render "shared/header" %>
<div class="container">
<h5 class="screen-name">投稿作品の編集</h5>
<div class="contents">

<%= form_with model: @work, local: true do |f| %>

<div class="row">
  <div class="col s12 m6 l6 xl6">
    <%= f.label :images, '作品画像（必須）' %><br>
    <div class="file-field input-field">
      <div class="btn">
        <span>画像選択</span>
        <%= f.file_field :images, name: 'work[images][]', multiple: :true %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="複数枚指定できます">
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m4 l2 xl2">
  <%= f.label :date, '作成日（必須）' %><br>
    <div class="datetime">
      <%= raw sprintf(
        f.date_select(
          :date,
          use_month_numbers: true,
          prompt:'---',
          start_year: Time.now.year,
          end_year: 1930,
          date_separator: '%s',
          class: ""),
        '<span class="text-baseline"> 年 </span>', '<span class="text-baseline"> 月 </span>') + '<span class="text-baseline"> 日 </span>'
      %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m6 l4 xl3">
    <%= f.label :scope_id, '公開範囲（必須）' %>
    <%= f.collection_select(:scope_id, Scope.all, :id, :value, {}, {}) %>
  </div>
</div>

<div class="row">
  <div class="input-field col s12">
    <%= f.text_field :title, class: "validate" %>
    <%= f.label :title, 'タイトル' %>
  </div>
</div>

<div class="row">
  <div class="input-field col s12">
    <%= f.text_area :description, class: "materialize-textarea" %>
    <%= f.label :description, '作品説明' %>
  </div>
</div>

<div class="button_wrapper">
  <%= button_tag '', class: 'btn-large waves-effect waves-light', type: 'button', onclick: 'submit();' do %>
    作品編集<i class="material-icons right">send</i>
  <% end %>
</div>

<% end %>
</div>
</div>

app/views/works/index.erb
<%= render "shared/header" %>
一覧

app/views/works/index.html.erb
<%= render "shared/header" %>
一覧

app/views/works/show.html.erb
<%= render "shared/header" %>
<div class="container">

<h5 class="screen-name"><%= @work.date.strftime("%Y年%-m月%-d日") %></h5>

<div class="right-align">
  <%= work_scope_icon(@work) %>
  <%= @work.scope.value %>
</div>

<% if edit_permission_check(@family) %>
  <div class="right-align">
    <%= link_to '編集', edit_work_path(@work) %>
    <span>｜</span>
    <%= link_to '削除', work_path(@work), method: :delete %>
  </div>
<% end %>

<div class='work-img-content'>
  <%# <div class="slider">
    <ul class="slides"> %>
      <%= image_tag @work.images[0], class:"work-box-img materialboxed" %>
    <%# </ul>
  </div> %>
</div>

<div class="work-title-wrapper">
  <span class="work-title"><%= @work.title %></span>
  <span class="work-creator">by <%= @work.creator.name %>(<%= age(@work.creator, @work.date)%>)</span>
</div>

<p><%= @work.description %></p>

</div>